source 'http://rubygems.org'

gem 'sequel', '4.15.0'
gem 'sinatra', '1.4.5'
gem 'slim', '2.1.0'

gem 'thin', '1.6.3'
gem 'kramdown', '1.5.0'

group :development do
	gem 'sqlite3'
end

group :production do
	gem 'pg'
end
